const fs=require('fs');
const source=fs.readFileSync('work/cifra-premium-rebuild.html','utf8').replace(/<script[\s\S]*?<\/script>/gi,'');
const landing=fs.readFileSync('work/landing-v6.html','utf8').trim();
const base=source.replace(/<section class="screen landing[\s\S]*?(?=<section class="screen contact-page)/,landing+'\n');
if(base===source) throw new Error('Landing section marker was not found.');
const core=fs.readFileSync('work/cifra-core.js','utf8');
const finance=fs.readFileSync('work/vystav-finance.js','utf8');
const ui=fs.readFileSync('work/vystav-ui.css','utf8');
const brand=fs.readFileSync('brand.css','utf8');
const landingCss=fs.readFileSync('landing.css','utf8');
const landingJs=fs.readFileSync('work/landing-v6.js','utf8');
const appCss=['app.css','enhancements.css','compliance-theme.css','light-polish.css','audit.css'].map(file=>fs.readFileSync(file,'utf8')).join(String.fromCharCode(10));
const logoData='data:image/svg+xml;base64,'+fs.readFileSync('outputs/assets/nacas-logo.svg').toString('base64');
const iconData='data:image/svg+xml;base64,'+fs.readFileSync('outputs/assets/nacas-icon.svg').toString('base64');
const loginData='data:image/jpeg;base64,'+fs.readFileSync('outputs/assets/vystav-login-studio.jpg').toString('base64');
const humanStoryData='data:image/jpeg;base64,'+fs.readFileSync('outputs/assets/vystav-human-story.jpg').toString('base64');
const qr=fs.readFileSync('work/vendor-qrcode.js','utf8');
const pdfFonts={regular:fs.readFileSync('assets/fonts/LiberationSans-Regular.ttf').toString('base64'),bold:fs.readFileSync('assets/fonts/LiberationSans-Bold.ttf').toString('base64')};
const libs='<script>window.NACAS_APP_CSS='+JSON.stringify(appCss.replaceAll('__NACAS_ICON__',iconData))+';window.NACAS_BRAND_ICON='+JSON.stringify(iconData)+';window.NACAS_PDF_FONTS='+JSON.stringify(pdfFonts)+'</script><script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script><script>'+qr+'</script><script src="https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js"></script><script src="https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js"></script><script type="module">import { encode, PaymentOptions, CurrencyCode } from "https://esm.sh/bysquare@4/pay"; window.bySquare={encode,PaymentOptions,CurrencyCode}; window.dispatchEvent(new Event("bysquare-ready"));</script><script>'+finance+'</script><script>'+core+'</script><script>'+landingJs+'</script>';
const branded=base.replaceAll('__NACAS_LOGO__',logoData).replaceAll('__NACAS_ICON__',iconData).replaceAll('__VYSTAV_LOGIN_STUDIO__',loginData).replaceAll('__VYSTAV_HUMAN_STORY__',humanStoryData);
const styled=branded.replace('</head>',()=>'<style id="nacas-product-ui">'+ui+'\n'+brand.replaceAll('__NACAS_ICON__',iconData)+'\n'+landingCss+'</style></head>');
const out=styled.replace('</body>',()=>libs+'</body>');
for(const f of ['index.html','outputs/faktury-dashboard.html']) fs.writeFileSync(f,out,'utf8');
fs.copyFileSync('tokens.css','outputs/tokens.css');
fs.copyFileSync('BRAND.md','outputs/NACAS-BRAND-MANUAL.md');
fs.copyFileSync('_redirects','outputs/_redirects');
fs.copyFileSync('_headers','outputs/_headers');
